### ISSUE TITLE
dataset.csv is missing

### ISSUE THREAD

**Issue by alexhutnik** [jtheiner/LegoBrickClassification#2]
When I try to generate the full data set with `python dataset/generate_dataset.py` I get the error:

```
Traceback (most recent call last):
  File "dataset/generate_dataset.py", line 13, in <module>
    df = pd.read_csv(dataset_path, encoding='utf-8', index_col='id')
  File "/home/alex/anaconda3/envs/fastai/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/alex/anaconda3/envs/fastai/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/alex/anaconda3/envs/fastai/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/alex/anaconda3/envs/fastai/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/alex/anaconda3/envs/fastai/lib/python3.6/site-packages/pandas/io/parsers.py", line 1906, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 380, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 687, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'data/dataset-15/dataset.csv' does not exist: b'data/dataset-15/dataset.csv'
```

**Comment by jtheiner** [comment]
Contact me for the resource files. Later, I will also provide these directly

**Comment by muhammadhamzahabibhashmi** [comment]
can you please provide the dataset.csv 
and I need this for all categories

**Comment by jtheiner** [comment]
I have uploaded the relevant CSV.
